spring:
  application:
    name: dg-mall-order-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 8098
eureka:
  client:
    #    healthcheck:
    #      enabled: true
    serviceUrl:
      defaultZone: http://admin:123123@localhost:8761/eureka/,http://admin:123123@localhost:8762/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: android
      client-secret: android
      access-token-uri: http://localhost:9500/oauth/token
    resource:
      id: check_token
      token-info-uri: http://localhost:9500/oauth/check_token # 配置check_token的url地址
      user-info-uri: http://localhost:9500/auth/getUser # 配置user-info-uri的url地址
      prefer-token-info: false