server:
  port: 8060
spring:
  application:
    name: example-rocketmq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: localhost:9876
        bindings:
          input: {consumer.orderly: true}
      bindings:
        input: {destination: rocketmq-test-topic, content-type: text/plain, group: rocketmq-test-group, consumer.maxAttempts: 1}

management:
  endpoints:
    web:
      exposure:
        include: '*'