spring:
  application:
    name: mesh-boot-admin
  security:
    user:
      name: "admin"
      password: "123123"
  cloud:
    nacos:
      enabled: true
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8020

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://admin:123123@127.0.0.1:8830/eureka/
      preferIpAddress: true

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
