spring:
  redis:
    host: localhost
    password:
    port: 6379
  cloud:
    nacos:
      remoteAddress: localhost
      discovery:
        enabled: true
        serverAddr: ${spring.cloud.nacos.remoteAddress}:8848
    sentinel:
      nacos:
        flowRule:
          groupId: SENTINEL_GROUP
          dataId: sentinel.gateway.flow.rule
      transport:
        port: 8720
        dashboard: localhost:8081
    gateway:
      enabled: true
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/product/**
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
        - id: business_service_route
          uri: lb://example-business-service
          predicates:
            - Path=/nacos/**,/bar/{segment}
#            - Cookie=JSESSIONID, 89B45328A3FF57837046CAAAE490916F
#            - Header=X-Request-Id, \d+
#            - Method=GET
#            - Query=baz
#            - RemoteAddr=192.168.1.1/20
          filters:
            - StripPrefix=1
#            - AddRequestHeader=X-Request-Foo, Bar
#            - AddRequestParameter=foo, bar
#            - AddResponseHeader=X-Response-Foo, Bar

spring.main.allow-bean-definition-overriding: true
management.endpoints.web.exposure.include: '*'

#Authorization Signature switch(True: Checking)
checkSign: false

# https://ahas.console.aliyun.com/?spm=a2cb8.12805554.0.0.6bf71e63lvtCGv#/SystemGuardGw?ns=default&regionId=public&isi=&_k=li7w04
#ahas:
#  namespace: default
#  license: c997cffd0c7148efa3e64042dfa6cca5
#project:
#  name: example-gateway
