spring:
  redis:
    host: localhost
    password:
    port: 6379
  cloud:
    nacos:
      discovery:
        enabled: true
        serverAddr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8888
        dashboard: localhost:8080
    gateway:
      enabled: true
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/product/**
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
        - id: business_service_route
          uri: lb://example-business-service
          predicates:
            - Path=/nacos/**,/bar/{segment}
#            - Cookie=JSESSIONID, 89B45328A3FF57837046CAAAE490916F
#            - Header=X-Request-Id, \d+
#            - Method=GET
#            - Query=baz
#            - RemoteAddr=192.168.1.1/20
          filters:
            - StripPrefix=1
#            - AddRequestHeader=X-Request-Foo, Bar
#            - AddRequestParameter=foo, bar
#            - AddResponseHeader=X-Response-Foo, Bar

#开启端点 sentinel.dashboard.auth.username=sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'

#Authorization Signature switch(True: Checking)
checkSign: false
