spring:
  application:
    name: dg-mall-cloud-boot-admin
  security:
    user:
      name: "admin"
      password: "123123"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8000

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
